AWSTemplateFormatVersion: 2010-09-09
Description: EFS Template - requires the Animals4Life base VPC Template v3. Exports a4l-vpc1-wordpress-efs can be used by other templates.
Metadata:
  Authors:
    Description: Adrian Cantrill (adrian@cantrill.io)
Resources:
  EFS:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: !Join [ '', [ 'A4L-EFS-WordPress / ', !Ref 'AWS::StackName' ] ]
  EFSMTA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFS
      SecurityGroups:
        - !ImportValue a4l-vpc1-default-instance-sg
      SubnetId: !ImportValue a4l-vpc1-subnet-appa
  EFSMTB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFS
      SecurityGroups:
        - !ImportValue a4l-vpc1-default-instance-sg
      SubnetId: !ImportValue a4l-vpc1-subnet-appb
  EFSMTC:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFS
      SecurityGroups:
        - !ImportValue a4l-vpc1-default-instance-sg
      SubnetId: !ImportValue a4l-vpc1-subnet-appc
Outputs:
  ElasticFileSystem:
    Value: !Ref EFS
    Export:
      Name: a4l-vpc1-wordpress-efs